### ISSUE TITLE
Double integral "\iint" and space characters "\," break the expressions

### ISSUE THREAD

**Issue by Lenny-the-burger** [FuriousChocolate/LaTeXmos#1]
Example:
 `L(\vec{p}) = \iint_{u+v \leq 1, u \geq 0, v \geq 0} R(\vec{p},\, u\vec{a} + v\vec{b} + (1-u-v)\vec{c})\, du\, dv` will not render.
`L(\vec{p}) = \int \int_{u+v \leq 1, u \geq 0, v \geq 0} R(\vec{p},\, u\vec{a} + v\vec{b} + (1-u-v)\vec{c}) du dv` will render.

Expected output (github markdown does not support the `\,` character):
$L(\vec{p}) = \iint_{u+v \leq 1, u \geq 0, v \geq 0} R(\vec{p},\, u\vec{a} + v\vec{b} + (1-u-v)\vec{c})\, du\, dv$

**Comment by FuriousChocolate** [comment]
Fixed!
`L(\vec{p}) = \iint_{u+v \leq 1, u \geq 0, v \geq 0} R(\vec{p},\, u\vec{a} + v\vec{b} + (1-u-v)\vec{c})\, du\, dv`
will now render properly.
